// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DailyLimitPriceInfo
{
    public DateOnly Date { get; set; }

    public string Pid { get; set; }

    public string Name { get; set; }

    public bool IsOtc { get; set; }

    public bool IsLimit { get; set; }

    public bool IsWarrant { get; set; }

    public bool IsMarginSellUnderRef { get; set; }

    public bool IsLendingSellUnderRef { get; set; }

    public double ReferencePrice { get; set; }

    public double LimitUpPrice { get; set; }

    public double LimitDownPrice { get; set; }

    public string DayTrade { get; set; }

    public double StrikePrice { get; set; }

    public double UpperLimit { get; set; }

    public double LowerLimit { get; set; }

    public double ExerciseRatio { get; set; }

    public double MatchTime { get; set; }

    public double BrokerOvernight { get; set; }

    public string ExpiryDate { get; set; }
}