// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DailyWarrantInfo
{
    public DateOnly Date { get; set; }

    public string Pid { get; set; }

    public string Name { get; set; }

    public bool IsOtc { get; set; }

    public bool IsCall { get; set; }

    public string SeccoName { get; set; }

    public string Underlying { get; set; }

    public string UnderlyingName { get; set; }

    public double Strike { get; set; }

    public double LimitUpPrice { get; set; }

    public double LimitDownPrice { get; set; }

    public double ExerciserRatio { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly LastTradeDate { get; set; }

    public DateOnly ExDate { get; set; }
}