// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DailyThreeTraderDeal
{
    public DateOnly Date { get; set; }

    public string Pid { get; set; }

    public double ForeignBay { get; set; }

    public double ForeignSell { get; set; }

    public double ForeignDealerBay { get; set; }

    public double ForeignDealerSell { get; set; }

    public double InvestmentBay { get; set; }

    public double InvestmentSell { get; set; }

    public double DealerBay { get; set; }

    public double DealerSell { get; set; }

    public double DealerHedgingBay { get; set; }

    public double DealerHedgingSell { get; set; }
}