// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DailyStockInfo
{
    public string Pid { get; set; }

    public string Name { get; set; }

    public bool IsOtc { get; set; }

    public string Country { get; set; }

    public string Industry { get; set; }
}