// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DailyQuote
{
    public DateOnly Date { get; set; }

    public string Pid { get; set; }

    public double Volume { get; set; }

    public double Open { get; set; }

    public double High { get; set; }

    public double Low { get; set; }

    public double Close { get; set; }

    public double LastBp { get; set; }

    public double LastAp { get; set; }
}