// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DailySpecialPidGroup
{
    public DateOnly Date { get; set; }

    public string Sysid { get; set; }

    public string Pid { get; set; }

    public double Volume { get; set; }

    public double Volume2 { get; set; }

    public double Volume3 { get; set; }
}