// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DailyWarrantCountInfo
{
    public DateOnly Date { get; set; }

    public string Pid { get; set; }

    public double Mp { get; set; }

    public double ImplyVol { get; set; }

    public double Delta { get; set; }

    public double VegaPcnt { get; set; }

    public double Leverage { get; set; }

    public double Strike { get; set; }

    public double StockPrice { get; set; }

    public double T { get; set; }

    public double Er { get; set; }

    public double ExDays { get; set; }
}