// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DailyHitRate
{
    public DateOnly Date { get; set; }

    public string Acno { get; set; }

    public string SysId { get; set; }

    public string SeccoName { get; set; }

    public int BayOrderCount { get; set; }

    public int BayDealCount { get; set; }

    public int SellOrderCount { get; set; }

    public int SellDealCount { get; set; }

    public int BayAddOrderCount { get; set; }

    public int BayAddDealCount { get; set; }

    public int SellAddOrderCount { get; set; }

    public int SellAddDealCount { get; set; }
}