// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DividendNoticeTable
{
    public DateOnly Date { get; set; }

    public string Pid { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public double FreeAllotmentRate { get; set; }

    public double CashAllotmentRate { get; set; }

    public double CashPrice { get; set; }

    public double CashDividend { get; set; }
}