// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class DividendTable
{
    public DateOnly Date { get; set; }

    public string Pid { get; set; }

    public string Name { get; set; }

    public int? Dividend { get; set; }

    public double? DividendQty { get; set; }

    public double? Seoqty { get; set; }

    public double? Seoprice { get; set; }

    public double? DividendPrice { get; set; }
}