// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class Holiday
{
    public DateOnly Date { get; set; }

    public bool IsHoliday { get; set; }

    public string Msg { get; set; }
}