// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class StockDealTest
{
    public string Seq { get; set; }

    public string OrderNo { get; set; }

    public DateTime Time { get; set; }

    public string SysId { get; set; }

    public string Acno { get; set; }

    public string Pid { get; set; }

    public double Price { get; set; }

    public int Qty { get; set; }

    public string Kind { get; set; }
}