// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class TwstockDayTradeDeal
{
    public DateOnly Date { get; set; }

    public string Pid { get; set; }

    public string IsStopBefSell { get; set; }

    public double Deal { get; set; }

    public double BayMoney { get; set; }

    public double SellMoney { get; set; }
}