// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class WarrantInfo
{
    public string Pid { get; set; }

    public bool IsOtc { get; set; }

    public string Name { get; set; }

    public string SeccoName { get; set; }

    public string Underlying { get; set; }

    public string UnderlyingName { get; set; }

    public double Strike { get; set; }

    public double UpperPrice { get; set; }

    public double LowerPrice { get; set; }

    public double ExerciseRatio { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly LastTradeDate { get; set; }

    public DateOnly ExDate { get; set; }

    public bool IsCall { get; set; }

    public string Type { get; set; }

    public DateTime UpdateTime { get; set; }
}