// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class WarrantBayVolCount
{
    public int Time { get; set; }

    public string Pid { get; set; }

    public double ImplyVol { get; set; }

    public double AvgImplyVol { get; set; }

    public double StockPrice { get; set; }

    public double WarrantPrice { get; set; }

    public bool IsOver { get; set; }
}