// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataMiningMonitor.Models;

public partial class WarrantVolDaily
{
    public DateOnly Date { get; set; }

    public string Pid { get; set; }

    public double AvgVol { get; set; }
}